seed ability
gmd298/personal-cms-api pull request #12
Opened 2022-09-21 18:26 UTC by gmd298

# Relevant ticket
seed

# Changes made

* added seed ability

# Steps to QA

* run ~npm run db:seed~

2022-09-23 20:07 UTC, gmd298 commented
Hello Mr. Benton. I am requesting you review this.

2022-09-24 18:18 UTC, JakeBent requested changes
minor changes, almost there.

2022-09-24 18:18 UTC, JakeBent commented on scripts/seeds/seed.js
> +  // await Promise.all(mongoose.connection.collections.array.map((collection)
rm comments

2022-09-24 18:18 UTC, JakeBent commented on src/server.js
> +  origin: 'http://localhost:3001',
store the string as a constant called `corsHost` in ` config/index.js` similar to `dbUrl`, `port`, etc.
No hardcoded strings in the `server.js` file, we need them all to be overwrite-able via an environment variable.

2022-10-04 17:14 UTC, JakeBent reviewed
LGTM

2022-10-04 17:15 UTC, JakeBent approved these changes

2022-10-04 17:15 UTC, merged